name: Lint lua code
run-name: luacheck
on:
  push:
    paths:
      - '*.lua'
  pull_request:
    types: [opened]

jobs:
  Lualint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        id: checkout
        uses: actions/checkout@v4
      - name: Fix noname function
        run: |-
          sed -Ei -e 's/^function\s?\((.*)\)$/local function test(\1) -- luacheck\: ignore 211/g' *.lua
      - name: Lucheck Linter
        id: lualint
        uses: lunarmodules/luacheck@v1
